### ISSUE TITLE
Transparent background?

### ISSUE THREAD

**Issue by Blankeos** [subframe7536/vscode-custom-ui-style#1]
Anyway to do it? Cool fork btw!

**Comment by subframe7536** [comment]
Just implement it following https://github.com/be5invis/vscode-custom-css/issues/236, and I havent tried it yet, cause I have no need for it.

You can setup `custom-ui-style.electron` just like apc to have a try

**Comment by Blankeos** [comment]
Thanks for the reply! Yeah I have tried:

```
"custom-ui-style.electron": {
   "transparent": true,
   "frame": false
}
```

No luck unfortunately.

**Comment by subframe7536** [comment]
Try to fix it using [`vscode-vibrancy-continued`](https://github.com/illixion/vscode-vibrancy-continued/blob/2581445d7d629a9a43d3767797a0de005d287ec6/extension/index.js#L396-L411)'s logic

Released in v0.2.1

**Comment by hologerry** [comment]
> Try to fix it using [`vscode-vibrancy-continued`](https://github.com/illixion/vscode-vibrancy-continued/blob/2581445d7d629a9a43d3767797a0de005d287ec6/extension/index.js#L396-L411)'s logic
> 
> Released in v0.2.1

I tested this version in VSCode insiders, but not work.

**Comment by subframe7536** [comment]
Well, I have no bandwidth and I'm not really feeling up to fixing this issue lately.

So, PR welcome 👋

**Comment by Blankeos** [comment]
Okay wait lol guys. It does actually work. Actually... I'm not sure which worked:
1. This extension.
2. Or this [monkey-patching solution](https://github.com/be5invis/vscode-custom-css/issues/236#issuecomment-2417431679). (this is basically what the extension does automatically) - I noticed that after I added my configs with @subframe7536 's extension, and open `code /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js`, I do see the changes though so the Monkey patch might not be needed, just change it in the config.

HERE'S THE KICKER, I found that, it does reflect the change after I restart the whole computer! Not "restarting" or "reloading" VSCode (I just slept and woke up again lol). Not sure how to simulate a whole restart without actually restarting.

Also for the vibrancy (blurriness of the window, it differs per OS, I'm on a Mac), can refer to this: https://www.electronjs.org/docs/latest/api/browser-window#winsetvibrancytype-macos. Or just refer to that page for all the other settings on electron.

SEE:


<img width="1176" alt="image" src="https://github.com/user-attachments/assets/e8536355-0cfd-40ef-b195-2f4c10c9dd50">

**Comment by subframe7536** [comment]
> HERE'S THE KICKER, I found that, it does reflect the change after I restart the whole computer! Not "restarting" or "reloading" VSCode (I just slept and woke up again lol). Not sure how to simulate a whole restart without actually restarting. `frame: false` does not seem to work though.

So, all the need to make it effect is just press `CMD + Q` ? I will add some tips in the `Restart` notification

**Comment by Blankeos** [comment]
`CMD + Q` doesn't work unfortunately. A whole restart seems to be needed to see the changes.

**Comment by Blankeos** [comment]
Anyway closing this since transparency is achieved. Vibrancy not yet though.

**Comment by CnsMaple** [comment]
@Blankeos hello, Can you share your theme and icon theme?
