### ISSUE TITLE
VSCode warning: "Installation appears to be corrupt [Unsupported]"

### ISSUE THREAD

**Issue by jdanbrown** [subframe7536/vscode-custom-ui-style#11]
Problem is the same as here:
- https://stackoverflow.com/questions/61028032/installation-appears-to-be-corrupt-unsupported-visual-studio-code/78996147
- https://code.visualstudio.com/docs/supporting/faq#_installation-appears-to-be-corrupt-unsupported

It doesn't prevent the extension from working, but it's annoying to have to dismiss on every edit-apply-restart cycle. How are you dealing with this?

Here's what I ended up with:
- Install this extension (from the stackoverflow thread above):
  - https://github.com/RimuruChan/vscode-fix-checksums
- Dev loop:
  1. Edit my custom-ui-style config ([example](https://github.com/drcika/apc-extension/issues/230#issuecomment-2540660147))
  2. VSCode command: "Custom UI Style: Reload"
  3. VSCode command: "Fix Checksums: Apply" (from the vscode-fix-checksums extension)
  4. Quit VSCode
  5. Open VSCode

Is there a better way?

**Comment by jdanbrown** [comment]
(Aside) I also wrote this really hacky `quitAndRestart` command to automate steps (iv–v) (note `osascript` is macos only):

```ts
export function activate(context: vscode.ExtensionContext) {
  context.subscriptions.push(
    vscode.commands.registerCommand('jdanbrown.quitAndRestart', async () => {
      // Distinguish "Visual Studio Code" vs. "Visual Studio Code - Insiders"
      const appName = vscode.env.appName;
      // vscode doesn't expose electron `app.quit(); app.relaunch()`, so we have to DIY this
      //  - Poll for the app to finish exiting, else the relaunch will do nothing
      //  - To relaunch, I do `.../bin/code` instead of `open -a "${appName}"` because the latter does nothing (with detach)
      //    - [claude] Maybe because `open` goes through macos LaunchServices, which gets messed up under detach 🤷
      const command = `
        osascript \
          -e 'quit app "${appName}"' \
          -e 'repeat with i from 1 to 100' \
          -e '  if not (application "${appName}" is running) then exit repeat' \
          -e '  delay 0.1' \
          -e 'end repeat' \
          && '/Applications/${appName}.app/Contents/Resources/app/bin/code'
      `;
      console.info(`[jdanbrown.quitAndRestart] spawn: ${command}`);
      // Must spawn (not exec) for the child process to keep running after our process exits
      //  - https://nodejs.org/api/child_process.html#child_processspawncommand-args-options
      const subprocess = spawn(command, {
        // Detach from the parent
        detached: true,
        stdio: 'ignore',
        // Run command in a shell
        shell: true,
      });
      // Prevent the parent from waiting for the detached child to exit
      subprocess.unref();
    }),
  );
}
```

**Comment by jdanbrown** [comment]
Higher level, it'd be really cool if there was a builtin way to automate the whole (1–5) as one command! Especially since we lost apc-extension's hot reload on css edits, and `Developer: Reload Window` hasn't been working for me for css edits in custom-ui-style (so I have to do a full quit and restart).

**Comment by subframe7536** [comment]
WOW I just know this wonderful extension!

I think I can try to migrate its code into my extension.

**Comment by subframe7536** [comment]
> Higher level, it'd be really cool if there was a builtin way to automate the whole (1–5) as one command! Especially since we lost apc-extension's hot reload on css edits, and `Developer: Reload Window` hasn't been working for me for css edits in custom-ui-style (so I have to do a full quit and restart).

This effect only in vscode<1.95

**Comment by subframe7536** [comment]
I've found a more mature approach to restart VSCode: https://github.com/zokugun/vscode-sync-settings/blob/master/src/utils/restart-app.ts

**Comment by subframe7536** [comment]
It's weird, after I reloaded the config with the latest commit, the config rollback to default😅

**Comment by subframe7536** [comment]
Release in V0.4.0

**Comment by jdanbrown** [comment]
Thanks! In `restartMacOS()`, wdyt about replacing the `delay 1` with the 0.1s/10s wait loop? It's more responsive (min wait time 0.1s instead of 1s), and also it handles cases when it takes longer than 1s to quit — in particular, if you quit vscode with any terminals open, vscode prompts the user before killing the terminal processes, and this user response will almost always take longer than 1s.
- Current `delay 1`: https://github.com/subframe7536/vscode-custom-ui-style/commit/b4229a203f164ad39702a03b8a91325b200c9c08#diff-f8226b16dc739d18f304f592dbf15274bb99c27cceb5435f8699009cf3d3aaf3R55
- Proposed delay 0.1s/10s:

```ts
          -e 'repeat with i from 1 to 100' \
          -e '  if not (application "${appName}" is running) then exit repeat' \
          -e '  delay 0.1' \
          -e 'end repeat' \
```

**Comment by subframe7536** [comment]
Thanks, I will test it later

**Comment by subframe7536** [comment]
You can test it [custom-ui-style-0.4.0-beta.0.zip](https://github.com/user-attachments/files/18174850/custom-ui-style-0.4.0-beta.0.zip)

**Comment by subframe7536** [comment]
Release in V0.4.1
