### ISSUE TITLE
issue for appreciation

### ISSUE THREAD

**Issue by jatindotdev** [subframe7536/vscode-custom-ui-style#2]
hey man, insane respect for this 🙌🏻

i was hoping if i could get what all are supported options in election configuration object, my need is removing the title bar. i tried the configuration options i used in APC didn't work 😔

**Comment by subframe7536** [comment]
https://github.com/user-attachments/assets/62df4d97-00af-4585-b4cb-f4cfa9c9450d

**Comment by subframe7536** [comment]
> where can i find the list of all props that are there for the electron config

https://github.com/subframe7536/vscode-custom-ui-style/issues/1#issuecomment-2423660217
