### ISSUE TITLE
Not working on latest vscode October update

### ISSUE THREAD

**Issue by lkuoch** [subframe7536/vscode-custom-ui-style#3]
On macos, with the latest vscode update the custom styles aren't applying :( @subframe7536 

https://code.visualstudio.com/updates/v1_95

<img width="241" alt="image" src="https://github.com/user-attachments/assets/4505d0d2-66ba-4f2e-9adc-d8e7d37991a9">

**Comment by subframe7536** [comment]
Seems work for me. 

Have you ever reload the config? Upgrading the VSCode itself will remove the modification and you will need to reload it manually.

**Comment by subframe7536** [comment]
Initially I tested on my Mac and everything works. But then tried Windows version, it indeed breaks.

Now it should be fixed in v0.3.0

**Comment by ubranch** [comment]
oh no sorry, it is

**Comment by Arelav** [comment]
> oh no sorry, it is but only after the manually restarting the VSCode

Oh, definitely. After upgrading to the latest version and manually quit it works again. Thanks a lot.

**Comment by luan** [comment]
I'm getting this error on 1.95 (macOS) when reloading:

```
Fail to execute action, RangeError: Maximum call stack size exceeded
```

**Comment by subframe7536** [comment]
@luan can you try to set `custom-ui-style.applyOnConfigurationChanged` to `false` and see if this error disappeared?

**Comment by luan** [comment]
> @luan can you try to set `custom-ui-style.applyOnConfigurationChanged` to `false` and see if this error disappeared?

Weirdly, it worked on one of my computers but not the other, I see someone else ran into this now too on #6 so maybe it's more generalized. But no, changing that setting didn't fix it on the computer that has the error.

**Comment by subframe7536** [comment]
@luan just enhance you VSCode's permissions, see [FAQ](https://github.com/subframe7536/vscode-custom-ui-style?tab=readme-ov-file#rangeerror-maximum-call-stack-size-exceeded)
