### ISSUE TITLE
Doesn't work on Jupyter Notebook

### ISSUE THREAD

**Issue by xiaotianxt** [subframe7536/vscode-custom-ui-style#4]
Hi, I'm from [this issue](https://github.com/drcika/apc-extension/issues/230) and happy to find your extension working!

Is it possible to format the Jupyter Notebook rendered result? I was able to achieve that in Apc Extension before.

Below is a picture with all text color set to red.

![Example](https://github.com/user-attachments/assets/cb04497b-4ffd-4a73-b233-e122bf06dda2)

Thanks for your consideration!

**Comment by subframe7536** [comment]
Seems that rendered result parts are located within webview.

Setup `custom-ui-style.webview.stylesheet` will effect.

**Comment by subframe7536** [comment]
Temporarily closed due to no reply

**Comment by xjtusjtu** [comment]
![Image](https://github.com/user-attachments/assets/a4f57344-dc04-4a5c-9fd4-54124ece372d)



![Image](https://github.com/user-attachments/assets/d79fdc99-bc2a-4c2e-aff1-9fee900467ab)

Hi! My settings are as above, but it doesn't work. Are there any possible solutions? Thanks
