### ISSUE TITLE
Reload fails on fresh install

### ISSUE THREAD

**Issue by smartinio** [subframe7536/vscode-custom-ui-style#6]
### Error
`Fail to execute action, RangeError: Maximum call stack size exceeded`

### Extension version
`v0.3.1`

### About VS Code

```
Version: 1.95.0 (Universal)
Commit: 912bb683695358a54ae0c670461738984cbb5b95
Date: 2024-10-28T20:16:24.561Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Darwin arm64 23.4.0
```

### Screenshots

![2024-11-01 at 07 39 15@2x](https://github.com/user-attachments/assets/f359ec27-08aa-4b59-ad7f-4c6a685bff9c)

![2024-11-01 at 07 41 49@2x](https://github.com/user-attachments/assets/4ede4d4a-0399-4a5f-9d91-c112de379d54)

**Comment by subframe7536** [comment]
Cannot reproduce on my Mac...

Here is a new test version with full logs: [custom-ui-style-0.3.2-beta.1.zip](https://github.com/user-attachments/files/17605276/custom-ui-style-0.3.2-beta.1.zip)

**Comment by smartinio** [comment]
@subframe7536

1. I renamed the file from `.zip` to `.vsix` and installed it via `Install from VSIX...`
2. The output channel now has `npm:Atomically error` before the error in the OP

**Comment by smartinio** [comment]
Alright, managed to fix the issue. The added hint lead me to see that `atomically` is used to interact with the filesystem, so I suspected it's the same issue that was present with APC (file permissions)

Works after running this and quitting/reopening VSCode (cmd + Q):
```bash
sudo chown -R $(whoami) "/Applications/Visual Studio Code.app"
```

**Comment by subframe7536** [comment]
Thanks fot testing! I will add this tip to README

**Comment by subframe7536** [comment]
Release in v0.3.2

**Comment by Nebula-Developer** [comment]
> sudo chown -R $(whoami) "/Applications/Visual Studio Code.app"

Just to add, for Linux it's usually `/opt/visual-studio-code`. That worked for me.
