### ISSUE TITLE
Not a bug just a little help

### ISSUE THREAD

**Issue by joaoKuchnir** [subframe7536/vscode-custom-ui-style#7]
is it possible to change the line height in the vscod file tree? f so, can you help with a style setting?  xD

**Comment by subframe7536** [comment]
It would be hard to implement it in CSS, because its position is controlled by offset, and `attr(data-index number)` is not supported in `calc()` currently.

```html
<div 
  class="monaco-list-row"
  role="treeitem"
  data-index="8"
  data-last-element="false"
  data-parity="even"
  aria-setsize="3"
  aria-posinset="1"
  id="list_id_2_8"
  aria-selected="false"
  aria-label="components"
  aria-level="2"
  aria-expanded="true"
  draggable="true"
  style="top: 176px;height: 22px;line-height: 22px;"
>
```

**Comment by subframe7536** [comment]
Someone provide a solution: https://github.com/drcika/apc-extension/issues/230#issuecomment-2470184740
