### ISSUE TITLE
Extension incorrectly patches VSCode 1.95.x and breaks application

### ISSUE THREAD

**Issue by DeltaRazero** [subframe7536/vscode-custom-ui-style#8]
The extension incorrectly parses VSCode application data, causing it to break the installation. Tested on 95.0, .1 and .2, as well as multiple extension versions to rule out the problem.

I've also tested with not setting any customization options, just applying/reloading/patching with no data breaks as well.

Strings look all messed up, and the whole functionality of VSCode seems broken.

```
Version: 1.95.2
Commit: e8653663e8840adaf45af01eab5c627a5af81807
Date: 2024-11-07T11:07:22.054Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22621
```

![image](https://github.com/user-attachments/assets/067e650d-99ac-4daf-928d-495ed8465db9)

**Comment by subframe7536** [comment]
Have you ever start VSCode without any other extension? I have tested on Windows and MacOS, and everything works. You can see the reproduction in #2

**Comment by Aworldc** [comment]
off topic but could you share how you got the vertical sidebar tabs in the screenshot above?

**Comment by DeltaRazero** [comment]
@subframe7536 
Sorry for my delayed response. No other extension was causing the issue.

It appeared that application cache of VSCode caused this to happen. I'm not sure which cache caused it but it was either by the data in the `Cache`, `CachedData` or `GPUCache` folders (I removed the contents inside all of these folders all at once). Once removed, using the reload command no longer breaks the installation. 
In extension to this, I also have trouble sometimes reloading/applying new or changed custom CSS, in that nothing seems to be applied. This can also be resolved by removing the cached data and reapplying/reloading.

Might be good to include this in a FAQ somewhere. If you think no further action is needed, you can close this issue.

---

@Aworldc
`workbench.activityBar.location": "top"`

**Comment by ackvf** [comment]
I don't experience any broken styles, but the styles from my overrides are not applied either. VSCode still warns me though that "Your Code installation appears to be corrupt.", which is expected. Still, no style changes are applied, even when I see this in Output
```
update script sha256 dQOsRQ61cBzqZwMrjmuzAoH/GZrHQiS2XLf9HG5HF/Q=
Config reload [c:\Users\Qwerty\AppData\Local\Programs\VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css]
Config reload [c:\Users\Qwerty\AppData\Local\Programs\VS Code\resources\app\out\main.js]
Config reload [c:\Users\Qwerty\AppData\Local\Programs\VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js]
Config reload [c:\Users\Qwerty\AppData\Local\Programs\VS Code\resources\app\out\vs\workbench\contrib\webview\browser\pre\index.html]
```

**Comment by subframe7536** [comment]
Thanks for your feedback. There is already have a FAQ in README: https://github.com/subframe7536/vscode-custom-ui-style?tab=readme-ov-file#faq

BTW, I stick my VSCode version to 1.94.2. There is a performance issue which cause high cpu usage in 1.95, and the reload button the longer instantly effect since it's resource load strategy changed.
